# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-log-activity
Version: 23
Release: %mkrel 1
Summary: Log activity for Sugar
License: GPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Log/Log-23.tar.bz2

Requires: gnome-vfs2  
Requires: gnome-python-gnomevfs  
Requires: sugar-toolkit >= 0.88.0

BuildRequires: gettext  
BuildRequires: sugar-toolkit >= 0.88.0

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
Log is an activity for developers to examine the log files that are generated
by system software and other activities. Logs can also be uploaded to servers
to allow support staff to assist with troubleshooting.

%prep
%setup -q -n Log-23


%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.Log

%clean
rm -rf %{buildroot}

%files -f org.laptop.Log.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc COPYING NEWS

