# NOTE: Please do not edit this file, it was auto generated by jhconvert
#       See http://wiki.sugarlabs.org/go/Deployment_Team/jhconvert for details

Name: sugar-log-activity
Version: 36
Release: 1
Summary: Log activity for Sugar
License: GPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Log/Log-%{version}.tar.bz2

Requires: sugar-toolkit-gtk3 >= 0.85.8
Requires: python-gi

BuildRequires: gettext  
BuildRequires: sugar-toolkit-gtk3 >= 0.85.8

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
Log is an activity for developers to examine the log files that are generated
by system software and other activities. Logs can also be uploaded to servers
to allow support staff to assist with troubleshooting.

%prep
%setup -q -n Log-%{version}


%build

rm -f MANIFEST
python setup.py build

%install
rm -rf %{buildroot}
python setup.py install --prefix=%{buildroot}/%{_prefix}
find %{buildroot} -name '*.py.orig' -print0 | xargs -0 rm -f
%find_lang org.laptop.Log

%clean
rm -rf %{buildroot}

%files -f org.laptop.Log.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc COPYING NEWS



%changelog
* Sat Sep 19 2009 Aleksey Lim <alsroot@mandriva.org> 23-1mdv2010.0
+ Revision: 444546
- Update to 23

* Tue Aug 11 2009 Aleksey Lim <alsroot@mandriva.org> 19-1mdv2010.0
+ Revision: 414903
- Sucrose 0.85.2

* Mon Apr 06 2009 Aleksey Lim <alsroot@mandriva.org> 18-1mdv2009.1
+ Revision: 364290
- Sucrose 0.84.2 release

* Mon Feb 23 2009 Aleksey Lim <alsroot@mandriva.org> 17-1mdv2009.1
+ Revision: 344229
- Sucrose 0.83.6 release

* Sun Jan 11 2009 Aleksey Lim <alsroot@mandriva.org> 16-1mdv2009.1
+ Revision: 328408
- initial commit

