# NOTE: Do not edit, file was generated by jhconvert

Name: sugar-log-activity
Version: 18
Release: %mkrel 1
Summary: Log activity for Sugar
License: GPL
Group: Graphical desktop/Other
Url: http://sugarlabs.org/

Source: http://download.sugarlabs.org/sources/sucrose/fructose/Log/Log-18.tar.bz2

Requires: gnome-vfs2  
Requires: gnome-python-gnomevfs  
Requires: sugar-toolkit >= 0.84.2

BuildRequires: gettext  
BuildRequires: sugar-toolkit >= 0.84.2

BuildRoot: %{_tmppath}/%{name}-%{version}-%{release}-root-%(%{__id_u} -n)
BuildArch: noarch

%description
Log is an activity for developers to examine the log files that are generated
by system software and other activities. Logs can also be uploaded to servers
to allow support staff to assist with troubleshooting.

%prep
%setup -q -n Log-18


%build
python  \
	setup.py \
	build

%install
rm -rf %{buildroot}
[ -f setup.py ] && chmod 0755 setup.py
python  \
	setup.py \
	install \
	--prefix=%{buildroot}/%{_prefix}
%find_lang org.laptop.Log

%clean
rm -rf %{buildroot}

%files -f org.laptop.Log.lang
%defattr(-,root,root,-)
%{_datadir}/sugar/activities/*
%doc COPYING NEWS

